apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
  # When activeDeadlineSeconds is more than 120, the validation webhook will reject the pod creation
  activeDeadlineSeconds: 150