apiVersion: v1
kind: Pod
metadata:
  name: validation-webhook
  labels:
    app.kubernetes.io/name: validation-webhook
spec:
  containers:
    - name: validation-webhook
      image: webhook:0.1.0
      imagePullPolicy: Never
      ports:
        - containerPort: 443
          name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: validation-webhook-svc
spec:
  selector:
    app.kubernetes.io/name: validation-webhook
  ports:
    - name: name-of-service-port
      protocol: TCP
      port: 8443
      targetPort: http-web-svc
