apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation-webhook
webhooks:
  - name: validation-webhook.default.svc.cluster.local
    admissionReviewVersions: ["v1"]
    sideEffects: "None"
    timeoutSeconds: 30
    failurePolicy: Fail
    clientConfig:
      service:
        name: validation-webhook-svc
        namespace: default
        path: "/crd"
        port: 8443
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
